### ISSUE TITLE
Is there a reason ProblemDocument doesn't extend Error?

### ISSUE THREAD

**Issue by viztastic** [PDMLab/http-problem-details#28]
Hi @AlexZeitler ,

This is just an architecture question. Is there a reason why ProblemDocument doesn't extend the Error class from within the library?

**Comment by AlexZeitler** [comment]
@viztastic We don't want to be treated as errors but plain objects instead. The `ProblemDocument` is just a representation of, but not the error itself.

**Comment by viztastic** [comment]
Ok that makes sense, thanks!
