### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by AlexZeitler** [PDMLab/http-problem-details#3]

**Comment by tpluscode** [comment]
Sorry for commenting on a closed issue, but I highly recommend [`conventional-chengelog`](https://github.com/conventional-changelog/conventional-changelog)

I've been using that lately on all of my projects and it's super cool to have the changelog and version number automated from git commit messages.

**Comment by AlexZeitler** [comment]
I would be more than happy to have this auto-generated. If you would like, you can send another PR with the required changes. I'll wait with the release for #4 until the `conventional-changelog` PR is merged then. Ok?

**Comment by AlexZeitler** [comment]
You can also add it to the downstream projects for `http-problem-details` if you like.

**Comment by tpluscode** [comment]
Ok, will add
