### ISSUE TITLE
Empty package installation

### ISSUE THREAD

**Issue by alindesign** [PDMLab/http-problem-details#7]
Hi there, 

I have recently tried to do a clean instalation, and looks like the package dist files are missing (image).

![image](https://user-images.githubusercontent.com/12038126/67624305-a7959a80-f837-11e9-801a-939042c47f83.png)

**Comment by AlexZeitler** [comment]
Sorry for the inconveniences. We just released 📦 version `0.1.2` on npm which includes the `dist` folder again.

**Comment by alindesign** [comment]
@AlexZeitler Thanks :blush:
